apiVersion: v1
kind: Pod
metadata:
  name: helloworld-config
  labels:
    app: helloworld-config
spec:
  containers:
  - name: k8s-demo
    image: tshaiman/hello-node
    ports:
    - containerPort: 7777
    volumeMounts:
    - name: config-volume
      mountPath: /usr/src/app/config/
  volumes:
    - name: config-volume
      configMap:
        name: node-config
        items:
        - key: default.yaml
          path: default.yaml
